[package]
name = "melodies-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

zeroize = {version="1.5.7", features = ["zeroize_derive"]}
