[package]
name = "melodies-ring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "*"
melodies-core = {path = "../core"}
zeroize = "1.5"
rand = {version = "0.8", features = ["getrandom"]}
